language: c

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  - docker run -t -v  /home/travis/build/JJ/p6-wikidata-API:/test  --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "apk update && apk add openssl-dev"

script:
  - docker run -t -v  /home/travis/build/JJ/p6-wikidata-API:/test  --entrypoint="/bin/sh" jjmerelo/test-perl6  -c cd /test && zef install .
  - docker run -t -v /home/travis/build/JJ/p6-wikidata-API:/test jjmerelo/test-perl6



