name: "Tests on source"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache installed dists
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Install and test
        run: docker run --rm -t --user root --entrypoint="/bin/sh" -v $(pwd):/test  ghcr.io/jj/raku-zef-gha -c "apk add --update --no-cache openssl-dev && cd /test && export HOME=/home/raku && zef install ."
